#!/bin/bash
echo "##############################################"
echo "Doc $1 dong dau tien tu tren xuong"
head -n $1 $3

echo "##############################################"
echo "Doc $2 dong dau tien tu duoi len cua 1 file"
tail -n $2 $3

echo "##############################################"
echo "Doc $1 dong dau tien tu tren xuong ke tu dong thu $2"
tail -n +$2 $3| head -n $1



